#+title: TMR May Ring
#+author: Protesilaos Stavrou
#+email: info@protesilaos.com
#+language: en
#+options: ':t toc:nil author:t email:t num:t
#+startup: content
#+macro: stable-version 1.1.0
#+macro: release-date 2025-04-18
#+macro: development-version 1.2.0-dev
#+export_file_name: tmr.texi
#+texinfo_filename: tmr.info
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_title: TMR May Ring: (tmr)
#+texinfo_dir_desc: Set timers using a convenient notation
#+texinfo_header: @set MAINTAINERSITE @uref{https://protesilaos.com,maintainer webpage}
#+texinfo_header: @set MAINTAINER Protesilaos Stavrou
#+texinfo_header: @set MAINTAINEREMAIL @email{info@protesilaos.com}
#+texinfo_header: @set MAINTAINERCONTACT @uref{mailto:info@protesilaos.com,contact the maintainer}

This manual, written by Protesilaos Stavrou, describes the customization
options for ~tmr~ (or TMR, TMR May Ring, ...), and provides every other
piece of information pertinent to it.  The name of the package is
pronounced as "timer" or "T-M-R".

The documentation furnished herein corresponds to stable version
{{{stable-version}}}, released on {{{release-date}}}.  Any reference to
a newer feature which does not yet form part of the latest tagged
commit, is explicitly marked as such.

Current development target is {{{development-version}}}.

+ Package name (GNU ELPA): ~tmr~
+ Official manual: <https://protesilaos.com/emacs/tmr>
+ Change log: <https://protesilaos.com/emacs/tmr-changelog>
+ Git repositories:
  + GitHub: <https://github.com/protesilaos/tmr>
  + GitLab: <https://gitlab.com/protesilaos/tmr>
+ Backronym: TMR May Ring; Timer Must Run.

#+toc: headlines 8 insert TOC here, with eight headline levels

* COPYING
:PROPERTIES:
:CUSTOM_ID: h:c002f811-ea06-4123-988b-a73183581fb9
:END:

Copyright (C) 2021-2025  Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below.  A copy of the license is
included in the section entitled “GNU Free Documentation License.”

(a) The FSF’s Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

* Overview
:PROPERTIES:
:CUSTOM_ID: h:7b3966d3-43c6-47f1-816a-8104f634bbd1
:END:
#+cindex: Overview of features

#+findex: tmr
TMR is an Emacs package that provides facilities for setting timers
using a convenient notation.  The first point of entry is the ~tmr~
command.  It prompts for a unit of time, which is represented as a
string that consists of a number and, optionally, a single character
suffix which specifies the unit of time.  Without a suffix, the number
is interpreted as a count in minutes.  Valid input formats:

| Input | Meaning   |
|-------+-----------|
| 5     | 5 minutes |
| 5m    | 5 minutes |
| 5s    | 5 seconds |
| 5h    | 5 hours   |

The input can be a floating point:

| Input | Meaning                  |
|-------+--------------------------|
| 1.5   | 1.5 minutes (90 seconds) |
| 1.5h  | 1.5 hours (90 minutes)   |

The input can also be an absolute time, such as =16:00= or =16:00:30=.
It sets a timer from present time until the one specified.

If ~tmr~ is called with an optional prefix argument (=C-u= with default
key bindings), it asks for a description to be associated with the given
timer.

#+findex: tmr-with-details
An alternative to the ~tmr~ command is ~tmr-with-details~.  The
difference between the two is that the latter always prompts for a
description and if the timer should be acknowledged.

#+findex: tmr-edit-description
The command ~tmr-edit-description~ can change the description a given
timer object.

#+findex: tmr-toggle-acknowledge
The command ~tmr-toggle-acknowledge~ toggles the acknowledge flag of a
given timer object.  A timer that needs to be acknowledged prompts for
confirmation after it elapses.  The user can either confirm and thus
dismiss the timer, or set a new duration for the next reminder, using
the familiar TMR input.

#+vindex: tmr-descriptions-list
The user option ~tmr-descriptions-list~ defines the completion
candidates that are shown at the description prompt.  Its value can be
either a list of strings or the symbol of a variable that holds a list
of strings.  The default value of ~tmr-description-history~, is the name
of a variable that contains input provided by the user at the relevant
prompt of the ~tmr~ and ~tmr-with-details~ commands.

When the timer is set, a message is sent to the echo area recording the
current time and the point in the future when the timer elapses.  Echo
area messages can be reviewed with the ~view-echo-area-messages~ which
is bound to =C-h e= by default.  To check all timers, use the command
~tmr-tabulated-view~, which has more features than the generic
=*Messages*= buffer ([[#h:51fe78e0-d614-492b-b7a3-fb6d5bd52a9a][Grid view]]).

#+findex: tmr-cancel
The ~tmr-cancel~ command cancels running timers without erasing them from
the list of created timer objects.  Timers at the completion prompt are
described by the exact time they were set and the input that was used to
create them, including the optional description that ~tmr~ and
~tmr-with-details~ accept.

#+findex: tmr-remove
The ~tmr-remove~ command is like ~tmr-cancel~, except it is not limited
to active timers: it can target elapsed ones as well.

#+findex: tmr-clone
The ~tmr-clone~ command directly copies the duration and optional
description of a timer into a new one.  With an optional prefix argument
(=C-u= by default), this command prompts for a duration.  If a double
prefix argument is supplied (=C-u C-u=), the command asks for a duration
and then a description.  The default values of such prompts are those of
the original timer.

#+findex: tmr-reschedule
The command ~tmr-reschedule~ changes the duration of the given timer to
a new one provided at the prompt.  In practice this is a shortcut to (i)
cloning the timer, (ii) prompting for duration, and (iii) cancelling the
original timer.

#+findex: tmr-remove-finished
The ~tmr-remove-finished~ command deletes all elapsed timers from the
list of timers.  This means that they can no longer be cloned.

#+vindex: tmr-confirm-single-timer
By default, TMR uses minibuffer completion to pick a timer object in
operations such as cloning and cancelling.  If the user option
~tmr-confirm-single-timer~ is set to nil, TMR will not use completion when
there is only one timer available: it will perform the specified command
outright.

Timers have hooks associated with their creation, cancellation, and
completion ([[#h:c908f440-da08-462e-be4e-a61fb274ecbc][Hooks]]).  TMR can also integrate with the desktop environment
to send notifications ([[#h:56bbbd6f-5b63-4375-9c86-e1eb231be356][Sound and desktop notifications]]).

#+vindex: tmr-prefix-map
TMR does not specify global key bindings. Instead, it sets up the
~tmr-prefix-map~, which specifies keys for the relevant commands. The
user has the option to either bind the map to a prefix key, such as
=C-c t= (so ~tmr~ is =C-c t t=), or bind individual commands to the
desired keys ([[#h:69eeb3fb-f11d-431e-ae16-2d9b322871cc][Sample configuration]]).

** Grid or tabulated view
:PROPERTIES:
:CUSTOM_ID: h:51fe78e0-d614-492b-b7a3-fb6d5bd52a9a
:END:
#+cindex: About tmr-tabulated and relevant commands

#+findex: tmr-tabulated-view
Timers can be viewed in a grid with ~tmr-tabulated-view~ (alias
~tmr-list-timers~). The data is placed in the =*tmr-tabulated-view*=
buffer and looks like this:

#+begin_example
Start      End        Remaining  Description
10:11:49   10:11:54   ✔
10:11:36   10:31:36   19m 35s
10:11:32   10:26:32   14m 31s    Yet another test
10:11:16   10:21:16   9m 14s     Testing how it works
#+end_example

If a timer has elapsed, it has a check mark associated with it,
otherwise the =Remaining= column shows the time left.  A =Description=
is shown only if it is provided while setting the timer, otherwise the
field is left blank.

Inside this grid view, all TMR commands that operate on timer objects
automatically target the one at point.  Whereas the global behaviour is
to use minibuffer completion to pick a timer to operate on.

The ~tmr-tabulated-view~ command relies on Emacs' ~tabulated-list-mode~.
From the =*tmr-tabulated-view*= buffer, one can invoke the command
~describe-mode~ (=C-h m= with standard key bindings) to learn about the
applicable functionality, such as how to expand/contract columns and
toggle sorting.

While in this grid view, one can perform all the operations on timers we
have already covered herein (the =C-h m= will show you their key
bindings in this mode).

#+vindex: tmr-list-timers-action-alist
The user option ~tmr-list-timers-action-alist~ controls how the
command ~tmr-tabulated-view~ displays its buffer. Its default
behaviour is to (i) place the buffer at the bottom of the Emacs frame,
(ii) resize the window to match the height of the buffer, and (iii)
select that window.

The value of this user option is the same data that is passed to
~display-buffer-alist~. It is meant to be customised by advanced
users. Evaluate =(info "(elisp) Displaying Buffers")= to read the
relevant entry in the manual.

The ~tmr-list-timers-action-alist~ is relevant only when the command
~tmr-tabulated-view~ is called interactively. In Lisp, the ~tmr-tabulated-view~
requires the buffer it should use and the concomitant action alist.

** Hooks
:PROPERTIES:
:CUSTOM_ID: h:c908f440-da08-462e-be4e-a61fb274ecbc
:END:
#+cindex: Hooks triggered by timer operations

TMR provides the following hooks:

#+vindex: tmr-timer-created-functions
+ ~tmr-timer-created-functions~ :: This is triggered by the ~tmr~ command.
  By default, it prints a message in the echo area showing the newly
  created timer's start and end time as well as its optional description
  (if provided).

#+vindex: tmr-timer-finished-functions
+ ~tmr-timer-finished-functions~ :: This runs when a timer elapses.  By
  default, it (i) produces a desktop notification which describes the
  timer's start/end time and optional description (if available), (ii)
  plays an alarm sound ([[#h:56bbbd6f-5b63-4375-9c86-e1eb231be356][Sound and desktop notifications]]), and (iii) prints
  a message in the echo area which is basically the same as the desktop
  notification.

#+vindex: tmr-timer-cancelled-functions
+ ~tmr-timer-cancelled-functions~ :: This is called by ~tmr-cancel~.  By
  default, it prints a message in the echo area describing the timer that
  was cancelled.

** Sound and desktop notifications
:PROPERTIES:
:CUSTOM_ID: h:56bbbd6f-5b63-4375-9c86-e1eb231be356
:END:
#+cindex: Alarm sound and settings for desktop notifications

#+vindex: tmr-sound-file
#+vindex: tmr-notification-urgency
Once the timer has run its course, it produces a desktop notification and
plays an alarm sound.  The notification's message is practically the same
as that which is sent to the echo area.

The sound file for the alarm is defined in ~tmr-sound-file~, while the
urgency of the notification can be set through the user option
~tmr-notification-urgency~.  Note that it is up to the desktop
environment or notification daemon to decide how to handle the urgency
value.

If the ~tmr-sound-file~ is nil, or the file is not found, no sound will
be played.

Sound playback depends on the =ffplay= executable which is part of
=ffmpeg=.

Desktop notifications work only if Emacs is built with DBus
functionality.  This is the norm.  If such functionality is not
available, TMR will issue a warning informing the user accordingly.

** Minibuffer histories
:PROPERTIES:
:CUSTOM_ID: h:fbedb656-2402-46bc-9763-d5112700c954
:END:

TMR defines two variables that store user input: ~tmr-duration-history~
and ~tmr-description-history~.  Minibuffer histories can persist between
sessions if the user enables the built-in =savehist= library.  Sample
configuration:

#+begin_src emacs-lisp
(require 'savehist)
(setq savehist-file (locate-user-emacs-file "savehist"))
(setq history-length 500)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history t)
(add-hook 'after-init-hook #'savehist-mode)
#+end_src

* Installation
:PROPERTIES:
:CUSTOM_ID: h:46378bdf-f6cc-469e-b0b0-1b90dd9aa595
:END:
#+cindex: Installation instructions

** GNU ELPA package
:PROPERTIES:
:CUSTOM_ID: h:807c2a8c-3d49-4fb3-bfb9-84d10675c95b
:END:

The package is available as ~tmr~.  Simply do:

: M-x package-refresh-contents
: M-x package-install

And search for it.

GNU ELPA provides the latest stable release.  Those who prefer to follow
the development process in order to report bugs or suggest changes, can
use the version of the package from the GNU-devel ELPA archive.  Read:
https://protesilaos.com/codelog/2022-05-13-emacs-elpa-devel/.

** Manual installation
:PROPERTIES:
:CUSTOM_ID: h:39fae83f-a49a-4887-8132-eb42e61919ea
:END:

Assuming your Emacs files are found in =~/.emacs.d/=, execute the
following commands in a shell prompt:

#+begin_src sh
cd ~/.emacs.d

# Create a directory for manually-installed packages
mkdir manual-packages

# Go to the new directory
cd manual-packages

# Clone this repo, naming it "tmr"
git clone https://github.com/protesilaos/tmr tmr
#+end_src

Finally, in your =init.el= (or equivalent) evaluate this:

#+begin_src emacs-lisp
;; Make Elisp files in that directory available to the user.
(add-to-list 'load-path "~/.emacs.d/manual-packages/tmr")
#+end_src

Everything is in place to set up the package.

* Sample configuration
:PROPERTIES:
:CUSTOM_ID: h:69eeb3fb-f11d-431e-ae16-2d9b322871cc
:END:
#+cindex: Package configuration

#+begin_src emacs-lisp
  ;; Set to nil to disable the sound
  (setq tmr-sound-file "/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga")

  ;; Desktop notification urgency level
  (setq tmr-notification-urgency 'normal)

  ;; Read the `tmr-descriptions-list' doc string
  (setq tmr-descriptions-list 'tmr-description-history)

  ;; Set global prefix bindings (autoloaded):
  (define-key global-map "\C-ct" 'tmr-prefix-map)

  ;; Alternatively bind tmr command (autoloaded):
  (define-key global-map "\C-ct" 'tmr)
#+end_src

* Integration with Embark
:PROPERTIES:
:CUSTOM_ID: h:64711ce4-c023-4f6e-b9aa-b43942013423
:END:

The =embark= package provides standards-compliant infrastructure to run
context-dependent actions on all sorts of targets (symbol at point, current
completion candidate, etc.). TMR is set up to make its timer objects
recognisable by Embark and registers the ~tmr-action-map~ in Embark.

* Acknowledgements
:PROPERTIES:
:CUSTOM_ID: h:047ecc52-ca02-4424-a037-c5b6a02383de
:END:
#+cindex: Contributors

TMR is meant to be a collective effort.  Every bit of help matters.

+ Authors :: Protesilaos Stavrou (maintainer), Damien Cassou, Daniel
  Mendler.

+ Contributions to the code or manual :: Christian Tietze, Ed Tavinor,
  Nathan R. DeGruchy.

* GNU Free Documentation License
:PROPERTIES:
:CUSTOM_ID: h:b8b7def2-5ab0-4623-b3ef-2a1bd17bb42a
:END:

#+texinfo: @include doclicense.texi

#+begin_export html
<pre>

                GNU Free Documentation License
                 Version 1.3, 3 November 2008


 Copyright (C) 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
     <https://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other
functional and useful document "free" in the sense of freedom: to
assure everyone the effective freedom to copy and redistribute it,
with or without modifying it, either commercially or noncommercially.
Secondarily, this License preserves for the author and publisher a way
to get credit for their work, while not being considered responsible
for modifications made by others.

This License is a kind of "copyleft", which means that derivative
works of the document must themselves be free in the same sense.  It
complements the GNU General Public License, which is a copyleft
license designed for free software.

We have designed this License in order to use it for manuals for free
software, because free software needs free documentation: a free
program should come with manuals providing the same freedoms that the
software does.  But this License is not limited to software manuals;
it can be used for any textual work, regardless of subject matter or
whether it is published as a printed book.  We recommend this License
principally for works whose purpose is instruction or reference.


1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that
contains a notice placed by the copyright holder saying it can be
distributed under the terms of this License.  Such a notice grants a
world-wide, royalty-free license, unlimited in duration, to use that
work under the conditions stated herein.  The "Document", below,
refers to any such manual or work.  Any member of the public is a
licensee, and is addressed as "you".  You accept the license if you
copy, modify or distribute the work in a way requiring permission
under copyright law.

A "Modified Version" of the Document means any work containing the
Document or a portion of it, either copied verbatim, or with
modifications and/or translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of
the Document that deals exclusively with the relationship of the
publishers or authors of the Document to the Document's overall
subject (or to related matters) and contains nothing that could fall
directly within that overall subject.  (Thus, if the Document is in
part a textbook of mathematics, a Secondary Section may not explain
any mathematics.)  The relationship could be a matter of historical
connection with the subject or with related matters, or of legal,
commercial, philosophical, ethical or political position regarding
them.

The "Invariant Sections" are certain Secondary Sections whose titles
are designated, as being those of Invariant Sections, in the notice
that says that the Document is released under this License.  If a
section does not fit the above definition of Secondary then it is not
allowed to be designated as Invariant.  The Document may contain zero
Invariant Sections.  If the Document does not identify any Invariant
Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed,
as Front-Cover Texts or Back-Cover Texts, in the notice that says that
the Document is released under this License.  A Front-Cover Text may
be at most 5 words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy,
represented in a format whose specification is available to the
general public, that is suitable for revising the document
straightforwardly with generic text editors or (for images composed of
pixels) generic paint programs or (for drawings) some widely available
drawing editor, and that is suitable for input to text formatters or
for automatic translation to a variety of formats suitable for input
to text formatters.  A copy made in an otherwise Transparent file
format whose markup, or absence of markup, has been arranged to thwart
or discourage subsequent modification by readers is not Transparent.
An image format is not Transparent if used for any substantial amount
of text.  A copy that is not "Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain
ASCII without markup, Texinfo input format, LaTeX input format, SGML
or XML using a publicly available DTD, and standard-conforming simple
HTML, PostScript or PDF designed for human modification.  Examples of
transparent image formats include PNG, XCF and JPG.  Opaque formats
include proprietary formats that can be read and edited only by
proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the
machine-generated HTML, PostScript or PDF produced by some word
processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself,
plus such following pages as are needed to hold, legibly, the material
this License requires to appear in the title page.  For works in
formats which do not have any title page as such, "Title Page" means
the text near the most prominent appearance of the work's title,
preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of
the Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose
title either is precisely XYZ or contains XYZ in parentheses following
text that translates XYZ in another language.  (Here XYZ stands for a
specific section name mentioned below, such as "Acknowledgements",
"Dedications", "Endorsements", or "History".)  To "Preserve the Title"
of such a section when you modify the Document means that it remains a
section "Entitled XYZ" according to this definition.

The Document may include Warranty Disclaimers next to the notice which
states that this License applies to the Document.  These Warranty
Disclaimers are considered to be included by reference in this
License, but only as regards disclaiming warranties: any other
implication that these Warranty Disclaimers may have is void and has
no effect on the meaning of this License.

2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either
commercially or noncommercially, provided that this License, the
copyright notices, and the license notice saying this License applies
to the Document are reproduced in all copies, and that you add no
other conditions whatsoever to those of this License.  You may not use
technical measures to obstruct or control the reading or further
copying of the copies you make or distribute.  However, you may accept
compensation in exchange for copies.  If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and
you may publicly display copies.


3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have
printed covers) of the Document, numbering more than 100, and the
Document's license notice requires Cover Texts, you must enclose the
copies in covers that carry, clearly and legibly, all these Cover
Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
the back cover.  Both covers must also clearly and legibly identify
you as the publisher of these copies.  The front cover must present
the full title with all words of the title equally prominent and
visible.  You may add other material on the covers in addition.
Copying with changes limited to the covers, as long as they preserve
the title of the Document and satisfy these conditions, can be treated
as verbatim copying in other respects.

If the required texts for either cover are too voluminous to fit
legibly, you should put the first ones listed (as many as fit
reasonably) on the actual cover, and continue the rest onto adjacent
pages.

If you publish or distribute Opaque copies of the Document numbering
more than 100, you must either include a machine-readable Transparent
copy along with each Opaque copy, or state in or with each Opaque copy
a computer-network location from which the general network-using
public has access to download using public-standard network protocols
a complete Transparent copy of the Document, free of added material.
If you use the latter option, you must take reasonably prudent steps,
when you begin distribution of Opaque copies in quantity, to ensure
that this Transparent copy will remain thus accessible at the stated
location until at least one year after the last time you distribute an
Opaque copy (directly or through your agents or retailers) of that
edition to the public.

It is requested, but not required, that you contact the authors of the
Document well before redistributing any large number of copies, to
give them a chance to provide you with an updated version of the
Document.


4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under
the conditions of sections 2 and 3 above, provided that you release
the Modified Version under precisely this License, with the Modified
Version filling the role of the Document, thus licensing distribution
and modification of the Modified Version to whoever possesses a copy
of it.  In addition, you must do these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct
   from that of the Document, and from those of previous versions
   (which should, if there were any, be listed in the History section
   of the Document).  You may use the same title as a previous version
   if the original publisher of that version gives permission.
B. List on the Title Page, as authors, one or more persons or entities
   responsible for authorship of the modifications in the Modified
   Version, together with at least five of the principal authors of the
   Document (all of its principal authors, if it has fewer than five),
   unless they release you from this requirement.
C. State on the Title page the name of the publisher of the
   Modified Version, as the publisher.
D. Preserve all the copyright notices of the Document.
E. Add an appropriate copyright notice for your modifications
   adjacent to the other copyright notices.
F. Include, immediately after the copyright notices, a license notice
   giving the public permission to use the Modified Version under the
   terms of this License, in the form shown in the Addendum below.
G. Preserve in that license notice the full lists of Invariant Sections
   and required Cover Texts given in the Document's license notice.
H. Include an unaltered copy of this License.
I. Preserve the section Entitled "History", Preserve its Title, and add
   to it an item stating at least the title, year, new authors, and
   publisher of the Modified Version as given on the Title Page.  If
   there is no section Entitled "History" in the Document, create one
   stating the title, year, authors, and publisher of the Document as
   given on its Title Page, then add an item describing the Modified
   Version as stated in the previous sentence.
J. Preserve the network location, if any, given in the Document for
   public access to a Transparent copy of the Document, and likewise
   the network locations given in the Document for previous versions
   it was based on.  These may be placed in the "History" section.
   You may omit a network location for a work that was published at
   least four years before the Document itself, or if the original
   publisher of the version it refers to gives permission.
K. For any section Entitled "Acknowledgements" or "Dedications",
   Preserve the Title of the section, and preserve in the section all
   the substance and tone of each of the contributor acknowledgements
   and/or dedications given therein.
L. Preserve all the Invariant Sections of the Document,
   unaltered in their text and in their titles.  Section numbers
   or the equivalent are not considered part of the section titles.
M. Delete any section Entitled "Endorsements".  Such a section
   may not be included in the Modified Version.
N. Do not retitle any existing section to be Entitled "Endorsements"
   or to conflict in title with any Invariant Section.
O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or
appendices that qualify as Secondary Sections and contain no material
copied from the Document, you may at your option designate some or all
of these sections as invariant.  To do this, add their titles to the
list of Invariant Sections in the Modified Version's license notice.
These titles must be distinct from any other section titles.

You may add a section Entitled "Endorsements", provided it contains
nothing but endorsements of your Modified Version by various
parties--for example, statements of peer review or that the text has
been approved by an organization as the authoritative definition of a
standard.

You may add a passage of up to five words as a Front-Cover Text, and a
passage of up to 25 words as a Back-Cover Text, to the end of the list
of Cover Texts in the Modified Version.  Only one passage of
Front-Cover Text and one of Back-Cover Text may be added by (or
through arrangements made by) any one entity.  If the Document already
includes a cover text for the same cover, previously added by you or
by arrangement made by the same entity you are acting on behalf of,
you may not add another; but you may replace the old one, on explicit
permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License
give permission to use their names for publicity for or to assert or
imply endorsement of any Modified Version.


5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this
License, under the terms defined in section 4 above for modified
versions, provided that you include in the combination all of the
Invariant Sections of all of the original documents, unmodified, and
list them all as Invariant Sections of your combined work in its
license notice, and that you preserve all their Warranty Disclaimers.

The combined work need only contain one copy of this License, and
multiple identical Invariant Sections may be replaced with a single
copy.  If there are multiple Invariant Sections with the same name but
different contents, make the title of each such section unique by
adding at the end of it, in parentheses, the name of the original
author or publisher of that section if known, or else a unique number.
Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History"
in the various original documents, forming one section Entitled
"History"; likewise combine any sections Entitled "Acknowledgements",
and any sections Entitled "Dedications".  You must delete all sections
Entitled "Endorsements".


6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other
documents released under this License, and replace the individual
copies of this License in the various documents with a single copy
that is included in the collection, provided that you follow the rules
of this License for verbatim copying of each of the documents in all
other respects.

You may extract a single document from such a collection, and
distribute it individually under this License, provided you insert a
copy of this License into the extracted document, and follow this
License in all other respects regarding verbatim copying of that
document.


7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate
and independent documents or works, in or on a volume of a storage or
distribution medium, is called an "aggregate" if the copyright
resulting from the compilation is not used to limit the legal rights
of the compilation's users beyond what the individual works permit.
When the Document is included in an aggregate, this License does not
apply to the other works in the aggregate which are not themselves
derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these
copies of the Document, then if the Document is less than one half of
the entire aggregate, the Document's Cover Texts may be placed on
covers that bracket the Document within the aggregate, or the
electronic equivalent of covers if the Document is in electronic form.
Otherwise they must appear on printed covers that bracket the whole
aggregate.


8. TRANSLATION

Translation is considered a kind of modification, so you may
distribute translations of the Document under the terms of section 4.
Replacing Invariant Sections with translations requires special
permission from their copyright holders, but you may include
translations of some or all Invariant Sections in addition to the
original versions of these Invariant Sections.  You may include a
translation of this License, and all the license notices in the
Document, and any Warranty Disclaimers, provided that you also include
the original English version of this License and the original versions
of those notices and disclaimers.  In case of a disagreement between
the translation and the original version of this License or a notice
or disclaimer, the original version will prevail.

If a section in the Document is Entitled "Acknowledgements",
"Dedications", or "History", the requirement (section 4) to Preserve
its Title (section 1) will typically require changing the actual
title.


9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document
except as expressly provided under this License.  Any attempt
otherwise to copy, modify, sublicense, or distribute it is void, and
will automatically terminate your rights under this License.

However, if you cease all violation of this License, then your license
from a particular copyright holder is reinstated (a) provisionally,
unless and until the copyright holder explicitly and finally
terminates your license, and (b) permanently, if the copyright holder
fails to notify you of the violation by some reasonable means prior to
60 days after the cessation.

Moreover, your license from a particular copyright holder is
reinstated permanently if the copyright holder notifies you of the
violation by some reasonable means, this is the first time you have
received notice of violation of this License (for any work) from that
copyright holder, and you cure the violation prior to 30 days after
your receipt of the notice.

Termination of your rights under this section does not terminate the
licenses of parties who have received copies or rights from you under
this License.  If your rights have been terminated and not permanently
reinstated, receipt of a copy of some or all of the same material does
not give you any rights to use it.


10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the
GNU Free Documentation License from time to time.  Such new versions
will be similar in spirit to the present version, but may differ in
detail to address new problems or concerns.  See
https://www.gnu.org/licenses/.

Each version of the License is given a distinguishing version number.
If the Document specifies that a particular numbered version of this
License "or any later version" applies to it, you have the option of
following the terms and conditions either of that specified version or
of any later version that has been published (not as a draft) by the
Free Software Foundation.  If the Document does not specify a version
number of this License, you may choose any version ever published (not
as a draft) by the Free Software Foundation.  If the Document
specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a
version permanently authorizes you to choose that version for the
Document.

11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any
World Wide Web server that publishes copyrightable works and also
provides prominent facilities for anybody to edit those works.  A
public wiki that anybody can edit is an example of such a server.  A
"Massive Multiauthor Collaboration" (or "MMC") contained in the site
means any set of copyrightable works thus published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0
license published by Creative Commons Corporation, a not-for-profit
corporation with a principal place of business in San Francisco,
California, as well as future copyleft versions of that license
published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in
part, as part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this
License, and if all works that were first published under this License
somewhere other than this MMC, and subsequently incorporated in whole or
in part into the MMC, (1) had no cover texts or invariant sections, and
(2) were thus incorporated prior to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site
under CC-BY-SA on the same site at any time before August 1, 2009,
provided the MMC is eligible for relicensing.


ADDENDUM: How to use this License for your documents

To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and
license notices just after the title page:

    Copyright (c)  YEAR  YOUR NAME.
    Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in the section entitled "GNU
    Free Documentation License".

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the "with...Texts." line with this:

    with the Invariant Sections being LIST THEIR TITLES, with the
    Front-Cover Texts being LIST, and with the Back-Cover Texts being LIST.

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of
free software license, such as the GNU General Public License,
to permit their use in free software.
</pre>
#+end_export

#+html: <!--

* Indices
:PROPERTIES:
:CUSTOM_ID: h:8372325e-67ee-48c5-83f3-7b5ef53f2db5
:END:

** Function index
:PROPERTIES:
:CUSTOM_ID: h:a2c585fd-3467-4aa5-a275-fea513438226
:END:

** Variable index
:PROPERTIES:
:CUSTOM_ID: h:5132c95a-116d-4144-89d3-a37fb0d01dcd
:END:

** Concept index
:PROPERTIES:
:CUSTOM_ID: h:4c85dc74-f64c-46a4-a5c6-9bd6275632be
:END:

#+html: -->
